# Generated by Django 5.1.4 on 2026-05-09 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='pdfs/%Y/%m/')),
                ('pdf_text', models.TextField(blank=True)),
                ('notes_content', models.TextField(blank=True, help_text='User-edited version of the extracted notes')),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='uploading', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('expected_answer', models.TextField(blank=True)),
                ('expected_keywords', models.JSONField(default=list)),
                ('order_index', models.IntegerField(default=0)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='notebooks.notebook')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True)),
                ('grade', models.CharField(choices=[('ungraded', 'Not Yet Graded'), ('correct', 'Correct'), ('partial', 'Partially Correct'), ('incorrect', 'Incorrect')], default='ungraded', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='notebooks.question')),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_duration', models.IntegerField(default=25)),
                ('break_duration', models.IntegerField(default=5)),
                ('cycles_completed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='notebooks.notebook')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_summary', models.TextField(blank=True)),
                ('key_points', models.JSONField(default=list, help_text='Key points extracted from the PDF')),
                ('missed_key_points', models.JSONField(default=list)),
                ('included_key_points', models.JSONField(default=list)),
                ('feedback_text', models.TextField(blank=True)),
                ('feedback_generated_at', models.DateTimeField(blank=True, null=True)),
                ('notebook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='notebooks.notebook')),
            ],
        ),
    ]
