# Generated by Django 5.1.4 on 2026-05-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the material'),
        ),
        migrations.AddField(
            model_name='summary',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Audio summary MP3 file', null=True, upload_to='audio/'),
        ),
    ]
