# Generated by Django 5.1.4 on 2026-05-09 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_summary_ai_summary_summary_audio_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Allow others to view this notebook'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_notebooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, default=list, help_text='List of choices for multiple choice questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('short_answer', 'Short Answer'), ('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank')], default='short_answer', max_length=20),
        ),
        migrations.AlterField(
            model_name='answer',
            name='grade',
            field=models.CharField(choices=[('ungraded', 'Not Yet Graded'), ('correct', 'Correct'), ('partial', 'Partially Correct'), ('incorrect', 'Incorrect')], db_index=True, default='ungraded', max_length=20),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='feedback_generated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['grade'], name='notebooks_a_grade_99d778_idx'),
        ),
        migrations.AddIndex(
            model_name='notebook',
            index=models.Index(fields=['user', '-created_at'], name='notebooks_n_user_id_85ff82_idx'),
        ),
        migrations.AddIndex(
            model_name='notebook',
            index=models.Index(fields=['status'], name='notebooks_n_status_ad4249_idx'),
        ),
        migrations.AddIndex(
            model_name='notebook',
            index=models.Index(fields=['is_public'], name='notebooks_n_is_publ_a9ec23_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['notebook', 'order_index'], name='notebooks_q_noteboo_6a465a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='notebooks_q_questio_16768a_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['notebook', '-started_at'], name='notebooks_s_noteboo_7ddec6_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['started_at'], name='notebooks_s_started_aeba7c_idx'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['feedback_generated_at'], name='notebooks_s_feedbac_711900_idx'),
        ),
    ]
