# Generated by Django 5.1.4 on 2026-05-09 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_notebook_is_public_notebook_share_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badge_type', models.CharField(choices=[('perfect_score', 'Perfect Score'), ('speed_learner', 'Speed Learner'), ('consistent', 'Consistent Learner'), ('master', 'Topic Master'), ('comeback', 'Comeback Kid'), ('milestone_10', '10 Questions'), ('milestone_50', '50 Correct Answers'), ('milestone_100', '100 Hours Studied'), ('sharing_guru', 'Sharing Guru'), ('first_export', 'Documentarian')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='bi-star-fill', max_length=50)),
                ('color', models.CharField(default='#fbbf24', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ClassStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('average_accuracy', models.FloatField(default=0.0)),
                ('most_difficult_topics', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Class Statistics',
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit_minutes', models.IntegerField(default=60)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('partial_answers', models.IntegerField(default=0)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_sequence', models.JSONField(default=list)),
                ('completed_topics', models.JSONField(default=list)),
                ('current_topic_index', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('achievement', 'Achievement Unlocked'), ('reminder', 'Study Reminder'), ('streak', 'Streak Alert'), ('group_invite', 'Group Invitation'), ('comment', 'New Comment'), ('system', 'System Message')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='bi-bell', max_length=50)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(default=1)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('repetitions', models.IntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(auto_now=True, db_index=True)),
                ('next_review', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('difficulty_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('invite_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions_answered', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('total_partial', models.IntegerField(default=0)),
                ('total_incorrect', models.IntegerField(default=0)),
                ('total_study_minutes', models.IntegerField(default=0)),
                ('study_streak_days', models.IntegerField(default=0)),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('overall_accuracy', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Study Analytics',
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('invite_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('max_members', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('is_verified_teacher', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.IntegerField(default=1)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Dark Theme'), ('light', 'Light Theme'), ('auto', 'Auto (System)')], default='dark', max_length=20)),
                ('primary_color', models.CharField(default='#2563eb', max_length=7)),
                ('secondary_color', models.CharField(default='#059669', max_length=7)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('normal', 'Normal'), ('large', 'Large'), ('xlarge', 'Extra Large')], default='normal', max_length=20)),
                ('reading_mode', models.BooleanField(default=False)),
                ('reduce_animations', models.BooleanField(default=False)),
                ('high_contrast', models.BooleanField(default=False)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('daily_reminder', models.BooleanField(default=True)),
                ('reminder_time', models.TimeField(default='09:00')),
                ('auto_save_enabled', models.BooleanField(default=True)),
                ('show_keyboard_shortcuts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='attempt_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='time_spent_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_answer_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notebook',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='extracted_images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='notebook',
            name='has_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notebook',
            name='is_scanned_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notebook',
            name='is_shared_to_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notebook',
            name='notes_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='ocr_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_choices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=2),
        ),
        migrations.AddField(
            model_name='question',
            name='is_flashcard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='matching_pairs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('short_answer', 'Short Answer'), ('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('multiple_select', 'Multiple Select'), ('matching', 'Matching Pairs'), ('ordering', 'Ordering/Sequence')], default='short_answer', max_length=20),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(blank=True, to='notebooks.question')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.AddField(
            model_name='notebook',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_notebooks', to='notebooks.assignment'),
        ),
        migrations.AddIndex(
            model_name='notebook',
            index=models.Index(fields=['is_scanned_pdf'], name='notebooks_n_is_scan_fe575c_idx'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='notebooks.notebook'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='exam_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='notebooks.examsession'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['user', '-updated_at'], name='notebooks_a_user_id_8dc6c8_idx'),
        ),
        migrations.AddField(
            model_name='groupcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupcomment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_comments', to='notebooks.question'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='notebook',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path', to='notebooks.notebook'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionreview',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='notebooks.question'),
        ),
        migrations.AddField(
            model_name='questionreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classstatistics',
            name='student_class',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='notebooks.studentclass'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='notebooks.studentclass'),
        ),
        migrations.AddField(
            model_name='studyanalytics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_study_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='members',
            field=models.ManyToManyField(related_name='study_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupcomment',
            name='study_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='notebooks.studygroup'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='notebooks.notebook'),
        ),
        migrations.AddField(
            model_name='topic',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependent_topics', to='notebooks.topic'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='notebooks.topic'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='notebooks_q_difficu_3f92e7_idx'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebooks.badge'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['user', '-started_at'], name='notebooks_e_user_id_feb505_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notebooks_n_user_id_8d6783_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notebooks_n_user_id_ca3a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='questionreview',
            index=models.Index(fields=['user', 'next_review'], name='notebooks_q_user_id_c0ff62_idx'),
        ),
        migrations.AddIndex(
            model_name='questionreview',
            index=models.Index(fields=['difficulty_score'], name='notebooks_q_difficu_77c332_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionreview',
            unique_together={('question', 'user')},
        ),
        migrations.AddIndex(
            model_name='groupcomment',
            index=models.Index(fields=['study_group', 'question'], name='notebooks_g_study_g_3c3ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'earned_at'], name='notebooks_u_user_id_035c22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'badge')},
        ),
    ]
