# Generated by Django 5.1.4 on 2026-05-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_badge_classstatistics_examsession_groupcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
