# Generated by Django 5.1.4 on 2026-05-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0005_question_needs_review_anki'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='processing_stage',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='pdf_file',
            field=models.FileField(upload_to='documents/%Y/%m/'),
        ),
    ]
