# Generated by Django 5.1.4 on 2026-09-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0009_notebookchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_math',
            field=models.BooleanField(default=False, help_text='Question text/answer contain LaTeX math - render with KaTeX and grade symbolically.'),
        ),
    ]
