# Generated by Django 5.1.4 on 2026-09-27 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0010_question_is_math'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='agent_note',
            field=models.CharField(blank=True, help_text='Why an agent created or flagged this question', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='source_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='notebooks.question'),
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('days', models.JSONField(blank=True, default=list)),
                ('rationale', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notebook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan', to='notebooks.notebook')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(choices=[('feedback', 'Feedback agent'), ('study_plan', 'Study-plan agent'), ('verifier', 'Question verifier'), ('coach', 'Tutor coach')], max_length=20)),
                ('trigger', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'Completed'), ('failed', 'Failed')], default='running', max_length=10)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('output', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='notebooks.notebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notebook', 'user', '-created_at'], name='notebooks_a_noteboo_7212fd_idx')],
            },
        ),
    ]
